---
# Source: rain-barrel-automation/templates/database/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rba-db-service
  labels:    
    environment: prod
    app: rain
    app.kuberenetes.io/name: rba-db-service
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    cnpg.io/cluster: rba-db-cluster
    cnpg.io/instanceRole: primary
---
# Source: rain-barrel-automation/templates/database/cluster.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: rba-db-cluster
  labels:    
    environment: prod
    app: rain
    app.kuberenetes.io/name: rba-db-cluster

spec:
  instances: 2

  storage:
    size: 100M
  
  monitoring:
    enablePodMonitor: true
