# Default values for website.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


globals:
  environment: prod
  appname: rain

services:
  web:
    service:
      listenPort: 80
      type: LoadBalancer
    app:
      listenPort: 8080
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
  db:
    cluster:
      clusterName: rba-db-cluster
      instances: 2
      size: 100M
      monitoring: true
    service:
      serviceName: rba-db-service