apiVersion: v1
kind: Deployment
metadata:
  name: mqtt-broker-deployment
  labels: {{- include "mqttbroker.deploymentlabels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "mqttbroker.matchlabels" . | indent 6 }}
  template:
    metadata:
      labels: {{- include "mqttbroker.brokerlabels" . | indent 8 }}
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto
          ports:
          - containerPort: 1883
          volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/
          resources: {{ .Values.services.mqtt.broker.resources | toYaml | nindent 12 }}
      volumes:
        - name: mosquitto-config
          configMap: 
            name: mosquitto-config
            defaultMode: 0644
