apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.mqtt.service.serviceName }}
  labels: {{- include "mqttbroker.servicelabels" . | indent 4}}
spec:
  type: LoadBalancer
  ports:
    - name: mosquitto
      port: 1883
      targetPort: 1883
      protocol: TCP
  selector: {{- include "mqttbroker.matchlabels" . | indent 4 }}
  loadBalancerIP: {{ .Values.services.mqtt.service.reservedIp }}