apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Values.services.db.cluster.clusterName }}
  labels: {{- include "dbcluster.labels" . | indent 4 }}
spec:
  instances: {{ .Values.services.db.cluster.instances }}
  storage:
    size: {{ .Values.services.db.cluster.size }}
  backup:
    barmanObjectStore:
      destinationPath: "gs://rain-barrel-automation/database-backups"
      googleCredentials:
        applicationCredentials:
          name: backup-creds
          key: gcsCredentials
  monitoring:
    enablePodMonitor: {{ .Values.services.db.cluster.monitoring }}
    
