apiVersion: v1
kind: Service
metadata:
  name: {{ include "website.fullname" . }}
  labels:
    {{- include "website.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.web.service.type }}
  ports:
    - port: {{ .Values.services.web.service.listenPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "website.selectorLabels" . | nindent 4 }}
