apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.web.app.name }}
  labels: {{- include "webapp.deploymentlabels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "webapp.matchlabels" . | indent 6 }}
  template:
    metadata:
      labels: {{- include "webapp.podlabels" . | indent 8 }}
    spec:
      containers:
        - name: django-webapp
          image: {{- include "webapp.image" . | indent 1}}
          imagePullPolicy: Always
          ports:
          - containerPort: 8000
          env:
          - name: BROKER_URL
            value: {{ .Values.services.mqtt.service.serviceName }}.default.svc.cluster.local
          - name: DATABASE_ENGINE
            value: django.db.backends.postgresql
          - name: DATABASE_NAME
            value: app
          - name: DATABASE_USER
            value: app
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rba-db-cluster-app
                key: password
          - name: DATABASE_HOST
            value: {{ .Values.services.db.service.internalRWServiceName }}.default.svc.cluster.local
          - name: DATABASE_PORT
            value: "5432"
          resources: {{ .Values.services.web.app.resources | toYaml | nindent 12 }}
