apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.web.service.serviceName }}
  labels: {{- include "webapp.servicelabels" . | indent 4}}
spec:
  type: LoadBalancer
  ports:
    - name: webapp
      port: 80
      targetPort: 80
      protocol: TCP
  selector: {{- include "webapp.matchlabels" . | indent 4 }}
  # loadBalancerIP: {{ .Values.services.mqtt.service.reservedIp }}